[package]
name = "sitemap"
version = "0.1.0"
authors = ["Hari Amoor <amoor.hari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.51"
log = "0.4.8"
